apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-java
  template:
    metadata:
      labels:
        app: backend-java
    spec:
      containers:
      - name: backend-java
        image: eduazureregistry1001.azurecr.io/backend-java:{{newTag}} # 이미지 주소 변경필요
        ports:
        - containerPort: 8080
