apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-vue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-vue
  template:
    metadata:
      labels:
        app: frontend-vue
    spec:
      containers:
      - name: frontend-vue
        image: eduazureregistry1001.azurecr.io/frontend-vue:{{newTag}} # 이미지 주소 변경필요
        ports:
        - containerPort: 80
